version: '3.8'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  go_project:
    build: go_project
    container_name: go_project
    tty: true
    environment:
      - IS_DOCKER=true
    ports:
      - "8080:8080"

  python_project:
    image: lakky1/hakata_python_project
    container_name: python_project
    tty: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATA_PATH=${DATA_PATH}
      - SITE_DATA_PATH=${SITE_DATA_PATH}
      - INDEX_PATH=${INDEX_PATH}
      - REDIS_PATH=redis:6379

  frontend_project:
    build:
      context: ./frontend_type_project
      dockerfile: Dockerfile
    ports:
      - "80:80"
